name: Notify new upstream release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/4 * * 1-5"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm init --yes
      - run: npm install semver

      - uses: actions/github-script@v5
        with:
          script: |
            const semver = require('semver');

            const { data: latestRelease } = await github.rest.repos.getLatestRelease({
              owner: 'microsoft',
              repo: 'vscode'
            });

            const releaseTag = latestRelease.tag_name;
            const nextReleaseTag = semver.inc(releaseTag, 'minor');
            const nextRelease = `release/${semver.major(nextReleaseTag)}.${semver.minor(nextReleaseTag)}`;
            console.log(nextRelease);

            const { data: releaseBranch} = await github.rest.repos.getBranch({
              owner: 'microsoft',
              repo: 'vscode',
              branch: nextRelease
            });
            console.log(releaseBranch);

      - name: Slack Notification
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: New vscode release branch created
          SLACK_MESSAGE: 'Start preparing for a new release :exclamation:'