name: Release the VS Code server bundles
on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-11, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - name: Check out the vscode repository
        run: git clone https://github.com/gitpod-io/vscode --depth=1 --branch web-server
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        working-directory: ./vscode
        run: yarn --frozen-lockfile --network-timeout 180000
      - name: Prepare for distribution
        working-directory: ./vscode
        run: yarn gulp server-min
      - if: runner.os == 'Windows'
        name: Download Node.js (Windows)
        run: |
          curl -o node.zip https://nodejs.org/dist/v14.17.5/node-v14.17.5-win-x64.zip
          Expand-Archive -LiteralPath node.zip -DestinationPath bundle/node
          mv bundle/node/node-*/* bundle/node/
          rm bundle/node-*/
      - if: runner.os == 'Linux'
        name: Download Node.js (Linux)
        run: |
          curl -o node.tar.xz https://nodejs.org/dist/v14.17.5/node-v14.17.5-linux-x64.tar.xz
          mkdir -p bundle/node
          tar -xvf node.tar.xz --directory=bundle/node
          mv bundle/node/node-*/* bundle/node/
          rm -rf bundle/node-*/
      - if: runner.os == 'macOS'
        name: Download Node.js (macOS)
        run: |
          curl -o node.tar.xz https://nodejs.org/dist/v14.17.5/node-v14.17.5-darwin-x64.tar.gz
          mkdir -p bundle/node
          tar -xvf node.tar.xz --directory=bundle/node
          mv bundle/node/node-*/* bundle/node/
          rm -rf bundle/node-*/
      - name: Move build output
        run: mv server-pkg/ bundle/
      - name: Get the VSC version (Linux & macOS)
        if: ${{ runner.os != 'Windows' }}
        run: echo "VERSION=$(./bundle/node/bin/node -p -e "require('./bundle/server-pkg/package.json').version")" >> $GITHUB_ENV
      - name: Determine archive filename
        uses: haya14busa/action-cond@v1
        id: archive
        with:
          cond: ${{ runner.os == 'Windows' }}
          if_true: code-web-server-v$(.\bundle\node\node.exe -p -e "require('.\bundle\server-pkg\package.json').version")-windows-x64.zip
          if_false: 'code-web-server-v$VERSION-${{ runner.os }}-x64.tar.gz'
      - if: runner.os != 'Windows'
        name: Create startup script (Linux & macOS)
        run: |
          curl -o bundle/startup.sh https://raw.githubusercontent.com/gitpod-io/vscode-releases/main/scripts/startup.sh
          chmod u+x bundle/startup.sh
          sudo chmod -R ugo-wrx ./bundle/node/bin/
          sudo chmod +rx ./bundle/node/bin/node
      - if: ${{ runner.os == 'Windows' }}
        name: Create startup script (Windows)
        run: curl -o bundle/startup.cmd https://raw.githubusercontent.com/gitpod-io/vscode-releases/main/scripts/startup.cmd
      - name: Bundle tarfile
        if: runner.os  != 'Windows'
        run: |
          sudo tar cfzv ${{ steps.archive.outputs.value }} bundle/ > /dev/null
      - name: Bundle zip
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path bundle\* -CompressionLevel Optimal -DestinationPath ${{ steps.archive.outputs.value }}
      - name: Archive sanity check
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-x64
          path: $(echo "${{ steps.archive.outputs.value }}")
      # - uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: ''
      #     bodyFile: 'A new release of Visual Studio Code server is out, you can find the downloads for the different platforms below.'
      #     repo: vscode
      #     token: ${{ secrets.GITHUB_TOKEN }} # Todo: add a token with more permissions
