name: Release the VS Code server bundles
on: [workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-11, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}      
    steps:
      - name: Check out the vscode repository
        run: git clone https://github.com/gitpod-io/vscode --depth=1 --branch web-server
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        working-directory: ./vscode
        run: yarn --frozen-lockfile --network-timeout 180000
      - name: Prepare for distribution
        working-directory: ./vscode
        run: yarn gulp server-min
      - if: runner.os == 'Windows'
        name: Download Node.js (Windows)
        run: |
          curl -o node.zip https://nodejs.org/dist/v14.17.5/node-v14.17.5-win-x64.zip
          Expand-Archive -LiteralPath node.zip -DestinationPath ${{ env.ARCHIVE_NAME }}/node
          mv ${{ env.ARCHIVE_NAME }}/node/node-*/* ${{ env.ARCHIVE_NAME }}/node/
          rm ${{ env.ARCHIVE_NAME }}/node-*/
      - if: runner.os == 'Linux'
        name: Download Node.js (Linux)
        run: |
          curl -o node.tar.xz https://nodejs.org/dist/v14.17.5/node-v14.17.5-linux-x64.tar.xz
          mkdir -p ${{ env.ARCHIVE_NAME }}/node
          tar -xvf node.tar.xz --directory=${{ env.ARCHIVE_NAME }}/node
          mv ${{ env.ARCHIVE_NAME }}/node/node-*/* ${{ env.ARCHIVE_NAME }}/node/
          rm -rf ${{ env.ARCHIVE_NAME }}/node-*/
      - if: runner.os == 'macOS'
        name: Download Node.js (macOS)
        run: |
          curl -o node.tar.xz https://nodejs.org/dist/v14.17.5/node-v14.17.5-darwin-x64.tar.gz
          mkdir -p ${{ env.ARCHIVE_NAME }}/node
          tar -xvf node.tar.xz --directory=${{ env.ARCHIVE_NAME }}/node
          mv ${{ env.ARCHIVE_NAME }}/node/node-*/* ${{ env.ARCHIVE_NAME }}/node/
          rm -rf ${{ env.ARCHIVE_NAME }}/node-*/
      - name: Move build output
        run: mv server-pkg/ ${{ env.ARCHIVE_NAME }}/
      - name: Determine archive filename
        uses: haya14busa/action-cond@v1
        id: archive
        with:
          cond: ${{ runner.os == 'Windows' }}
          if_true: 'zip'
          if_false: 'tar.gz'
      - name: Set environment variables (Linux & macOS)
        if: runner.os != 'Windows'
        run: |
          echo "EXTENSION=${{ steps.archive.outputs.value }}" >> $GITHUB_ENV
          echo "VERSION=$(node -p -e "require('./vscode/package.json').version")" >> $GITHUB_ENV
      - name: Set environment variables (Windows)
        if: runner.os == 'Windows'
        run: |
          chcp 65001
          echo ("ARCHIVE_NAME=code-web-server-v" + $(node -p -e "require('./vscode/package.json').version")+"-${{ runner.os }}-x64.${{ steps.archive.outputs.value }}") >> $env:GITHUB_ENV
      - name: Set archive file name
        run: echo "ARCHIVE_NAME=code-web-server-v${{ env.VERSION }}-${{ runner.os }}-x64.${{ env.EXTENSION }}" >> $GITHUB_ENV
      - if: runner.os != 'Windows'
        name: Create startup script (Linux & macOS)
        run: |
          curl -o ${{ env.ARCHIVE_NAME }}/startup.sh https://raw.githubusercontent.com/gitpod-io/vscode-releases/main/scripts/startup.sh
          chmod u+x ${{ env.ARCHIVE_NAME }}/startup.sh
          sudo chmod -R ugo-wrx ./${{ env.ARCHIVE_NAME }}/node/bin/
          sudo chmod +rx ./${{ env.ARCHIVE_NAME }}/node/bin/node
      - if: ${{ runner.os == 'Windows' }}
        name: Create startup script (Windows)
        run: curl -o ${{ env.ARCHIVE_NAME }}/startup.cmd https://raw.githubusercontent.com/gitpod-io/vscode-releases/main/scripts/startup.cmd
      - name: Bundle tarfile
        if: runner.os  != 'Windows'
        run: |
          sudo tar cfzv ${{ env.ARCHIVE_NAME }} ${{ env.ARCHIVE_NAME }}/ > /dev/null
      - name: Bundle zip
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path bundle\* -CompressionLevel Optimal -DestinationPath ${{ env.ARCHIVE_NAME }}
      - name: Archive sanity check
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-x64
          path: ${{ env.ARCHIVE_NAME }}
      # - uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: ''
      #     bodyFile: 'A new release of Visual Studio Code server is out, you can find the downloads for the different platforms below.'
      #     repo: vscode
      #     token: ${{ secrets.GITHUB_TOKEN }} # Todo: add a token with more permissions
