name: Release the VS Code server bundles
on: [workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the vscode repository
        uses: actions/checkout@v2
        with:
          repository: gitpod-io/vscode
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        # Todo
        run: echo Building
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ""
          bodyFile: "A new release of Visual Studio Code server is out, you can find the downloads for the different platforms below."
          repo: vscode
          token: ${{ secrets.GITHUB_TOKEN }} # Todo: add a token with more permissions
