name: Release the VS Code server bundles
on: [workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the vscode repository
        run: git clone https://github.com/gitpod-io/vscode --depth=1 --branch web-server
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install dependencies
        working-directory: ./vscode
        run: yarn
      - name: Prepare for distribution
        working-directory: ./vscode
        run: | 
          yarn gulp server-min
      - name: Determine archive filename
        uses: haya14busa/action-cond@v1
        id: archive
        with:
          cond: ${{ runner.os == "Windows" }}
          if_true: 'windows.zip'
          if_false: '${{ runner.os }}.tar.gz'
      - name: Bundle tarfile
        if: ${{ runner.os  != "Windows"}}
        run: |
          tar cfzv ${{ steps.archive.outputs.value }} server-pkg/
      - name: Bundle zip
        if: ${{ runner.os == "Windows" }}
        run: |
          Compress-Archive -LiteralPath ./server-pkg/ -DestinationPath ./windows.zip
      - name: Archive sanity check
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ${{ steps.archive.outputs.value }}
      # - uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: ""
      #     bodyFile: "A new release of Visual Studio Code server is out, you can find the downloads for the different platforms below."
      #     repo: vscode
      #     token: ${{ secrets.GITHUB_TOKEN }} # Todo: add a token with more permissions
