name: Release the VS Code server bundles
on: [workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the vscode repository
        run: git clone https://github.com/gitpod-io/vscode --depth=1 --branch web-server
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        working-directory: ./vscode
        run: yarn
      - name: Prepare for distribution
        working-directory: ./vscode
        run: | 
          yarn gulp server-min
      - name: Bundle tarfile
        run: |
          tar cfzv b.tar.gz server-pkg/
      # - uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: ""
      #     bodyFile: "A new release of Visual Studio Code server is out, you can find the downloads for the different platforms below."
      #     repo: vscode
      #     token: ${{ secrets.GITHUB_TOKEN }} # Todo: add a token with more permissions
