name: Openvscode server nightly
on: workflow_dispatch
  #schedule:
  #  - cron: '0 18 * * 1-5'

jobs:
  sync:
    name: Syncing web-server branch
    runs-on: ubuntu-18.04
    # timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.VSCODE_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'gitpod-io/openvscode-server'
          ref: 'next'
          fetch-depth: 0
      
      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0 libgbm1
          sudo cp build/azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
          sudo chmod +x /etc/init.d/xvfb
          sudo update-rc.d xvfb defaults
          sudo service xvfb start

      - uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Sync and run smoke tests
        id: syncAndRunSmokeTests
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          ./scripts/sync-with-upstream.sh

      - name: Push validated changes to next branch
        run: |
          git push origin next:next2 --force

      - name: Send mail
        if: ${{ failure() && steps.syncAndRunSmokeTests.outcome == 'failure' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Openvscode server nightly workflow failed
          to: jeanpierre@gitpod.io #,anton@gitpod.io
          from: Github Action Runner
          body: "Openvscode server nightly workflow #${{ github.run_number }} failed!"

      - name: Publish logs files
        if: ${{ failure() && steps.syncAndRunSmokeTests.outcome == 'failure' }}
        uses: actions/upload-artifact@v2
        with:
          name: logs-linux-web-server
          path: .build/logs
