name: Openvscode server nightly
on: workflow_dispatch
  #schedule:
  #  - cron: '0 18 * * 1-5'

jobs:
  sync:
    name: Syncing web-server branch
    runs-on: ubuntu-18.04
    # timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.VSCODE_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'gitpod-io/openvscode-server'
          ref: 'next'
          fetch-depth: 0
      
      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0 libgbm1
          sudo cp build/azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
          sudo chmod +x /etc/init.d/xvfb
          sudo update-rc.d xvfb defaults
          sudo service xvfb start

      - uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Compute node modules cache key
        id: nodeModulesCacheKey
        run: echo "::set-output name=value::$(node build/azure-pipelines/common/computeNodeModulesCacheKey.js)"
      - name: Cache node modules
        id: cacheNodeModules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-cacheNodeModules14-${{ steps.nodeModulesCacheKey.outputs.value }}
          restore-keys: ${{ runner.os }}-cacheNodeModules14-
      - name: Get yarn cache directory path
        id: yarnCacheDirPath
        if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn directory
        if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarnCacheDirPath.outputs.dir }}
          key: ${{ runner.os }}-yarnCacheDir-${{ steps.nodeModulesCacheKey.outputs.value }}
          restore-keys: ${{ runner.os }}-yarnCacheDir-
      - name: Execute yarn
        if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
        run: yarn --frozen-lockfile --network-timeout 180000

      - name: Sync with upstream (rebase)
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          ./scripts/sync-with-upstream.sh upstream/main next true

      - name: Compile
        run: |
          yarn server:init

      - name: Run smoke tests
        id: runSmokeTests
        run: |
          yarn smoketest --web --headless --electronArgs="--disable-dev-shm-usage --use-gl=swiftshader"

      - name: Send mail
        if: ${{ failure() && steps.runSmokeTests.outcome == 'failure' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Openvscode server nightly workflow failed
          to: jeanpierre@gitpod.io #,anton@gitpod.io
          from: Github Action Runner
          body: "Openvscode server nightly workflow #${{ github.run_number }} failed!"

      - name: Publish logs files
        if: ${{ failure() && steps.runSmokeTests.outcome == 'failure' }}
        uses: actions/upload-artifact@v2
        with:
          name: logs-linux-web-server
          path: .build/logs
