name: Openvscode server nightly
on: workflow_dispatch
  #schedule:
  #  - cron: '0 18 * * 1-5'

jobs:
  sync:
    name: Syncing web-server branch
    runs-on: ubuntu-latest
    # timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.VSCODE_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'gitpod-io/openvscode-server'
          ref: 'next'
          fetch-depth: 0
      
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Sync and run smoke tests
        id: syncAndRunSmokeTests
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          ./scripts/sync-with-upstream.sh

      - name: Push validated changes to next branch
        run: |
          git push origin next:next2 --force

      - name: Send mail
        if: ${{ failure() && steps.syncAndRunSmokeTests.outcome == 'failure' }} 
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Openvscode server nightly workflow failed
          to: jeanpierre@gitpod.io #,anton@gitpod.io
          from: Github Action Runner
          body: "Openvscode server nightly workflow #${{ github.run_number }} failed!"
